config/routes.rb
Rails.application.routes.draw do
  
  get 'manage/tardies'
  match '/atrasos' => 'manage#tardies', via: [:get, :post]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :books do
    resources :rents, :except => [:edit,:show,:index]
  end  

  root to: "manage#home"

end

app/models/authentication_provider.rb
class AuthenticationProvider < ActiveRecord::Base
  has_many :users
  has_many :user_authentications
end

app/models/book.rb
class Book < ActiveRecord::Base

	has_many :rents

	def self.search(search)
		if search.present?
			where('title @@ :q', q: search)
		else
			[]
		end
	end	

end

app/models/rent.rb
class Rent < ActiveRecord::Base

	belongs_to :book
	

	def self.tardy
		lates = []
		Rent.all.each do |r|

			if r.due_date < DateTime.now
				
				lates << r
			end
		
		end	
		return lates
	end	

	def self.warn(lates)

		lates.each do |r|

			RentMailer.rent_late(r).deliver
		
		end	

	end	
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_from_omniauth(params)
    attributes = {
      email: params['info']['email'],
      password: Devise.friendly_token
    }

    create(attributes)
  end

  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider

  serialize :params

  def self.create_from_omniauth(params, user, provider)
    token_expires_at = params['credentials']['expires_at'] ? Time.at(params['credentials']['expires_at']).to_datetime : nil

    create(
      user: user,
      authentication_provider: provider,
      uid: params['uid'],
      token: params['credentials']['token'],
      token_expires_at: token_expires_at,
      params: params,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def pesquisa
    if params[:search]
      @pesquisa = Book.search(params[:search])
    else
      @pesquisa = []
    end
  end 

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :pesquisa
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @title = "Todos os livros"
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @title = @book.title
  end

  # GET /books/new
  def new
    @book = Book.new
    @title = "Criando um livro"
  end

  # GET /books/1/edit
  def edit
    @title = "Editando livro"
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        flash[:success] = "Livro criado!"
        format.html { redirect_to @book }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        flash[:success] = "Informações do livro atualizadas"
        format.html { redirect_to @book}
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      flash[:success] = "Livro apagado!"
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :category_id, :taken)
    end
end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  
  def tardies
  
  	@books = Book.all
  	@title = "Emprestimos atrasados"

  end

  def home
  	@books = Book.all
  	@title = "Inicial"
  end	

end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rents = Rent.all
    respond_with(@rents)
  end

  def new
    @book = Book.find(params[:book_id])
    @rent = @book.rents.new
    @title = "Aluguel do livro " + @book.title 

    respond_with(@rent)
  end

  def create
    @book = Book.find(params[:book_id])
    
    if @book.rents.empty? 
      
      @rent = @book.rents.new(rent_params)
      @rent.save
      respond_to do |format|
        if @rent.save
          @book.update(taken: true)
          @book.save
          
          RentMailer.delay(run_at: 2.minutes.from_now).rent_confirmation(@rent)
          RentMailer.delay(run_at: @rent.due_date).rent_warning(@rent)
          RentMailer.delay(run_at: @rent.due_date).rent_end(@rent)
          
          flash[:success] = "Parabéns livro alugado!"
          format.html { redirect_to @rent.book }         
        else
          format.html { render :new }
        end
      end  

    else   
      respond_to do |format|
         flash[:danger] = "Livro já alugado!"
         format.html { redirect_to @book } 
      end 
    end
     
  end

  def update
    @rent.update(rent_params)
    #respond_with(@rent)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @rent.destroy
    respond_to do |format|
      if @rent.save
        @book.update(taken: false)
        @book.save
        
        flash[:success] = "Parabéns livro devolvido!"
        format.html { redirect_to @rent.book }
      else
        format.html { render :new }
      end
    end  
  end

  private
    def set_rent
      @rent = Rent.find(params[:id])
    end

    def rent_params
      params.require(:rent).permit(:name, :email, :due_date)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google
    create
  end

  private

    def create
      auth_params = request.env["omniauth.auth"]
      provider = AuthenticationProvider.where(name: auth_params.provider).first
      authentication = provider.user_authentications.where(uid: auth_params.uid).first
      existing_user = current_user || User.where('email = ?', auth_params['info']['email']).first

      if authentication
        sign_in_with_existing_authentication(authentication)
      elsif existing_user
        create_authentication_and_sign_in(auth_params, existing_user, provider)
      else
        create_user_and_authentication_and_sign_in(auth_params, provider)
      end
    end

    def sign_in_with_existing_authentication(authentication)
      sign_in_and_redirect(:user, authentication.user)
    end

    def create_authentication_and_sign_in(auth_params, user, provider)
      UserAuthentication.create_from_omniauth(auth_params, user, provider)

      sign_in_and_redirect(:user, user)
    end

    def create_user_and_authentication_and_sign_in(auth_params, provider)
      user = User.create_from_omniauth(auth_params)
      if user.valid?
        create_authentication_and_sign_in(auth_params, user, provider)
      else
        flash[:error] = user.errors.full_messages.first
        redirect_to new_user_registration_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/manage_helper.rb
module ManageHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "erro") %> proíbiram este livro de ser salvo:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Título" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author, "Autor" %><br>
    <%= f.text_field :author %>
  </div>
  <%= f.hidden_field :taken, :value => false %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editando <%= @book.title%> </h1>

<%= render 'form' %>

<%= link_to 'Voltar', @book, :class => "btn btn-default" %>

app/views/books/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Book', new_book_path %>
<% end %>

app/views/books/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="col-md-12">
  <% if @book.taken %>

    <div class="panel panel-danger">
  
  <% else %>

    <div class="panel panel-success">
  
  <% end %> 
    <div class="panel-heading"><h3><%= @book.title %></h3></div>

    <div class="panel-body">
    <p>
      <strong>Autor:</strong>
      <%= @book.author %>
    </p>
    </div>
  
  </div>
  </div>  

  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">Alugueis deste livro:</div>
      <div class="panel-body">
          <% if @book.taken? %>
          	
          	<% @book.rents.each do |rent| %>

          		<p>
                <strong>Locatário:</strong>
                <%= rent.name %>
              </p>
              <p>
                <strong>Data de devolução:</strong>
                <%= rent.due_date.strftime("%d / %m / %Y")  %>
              </p>
              <p><%= link_to 'Devolver o livro',[@book, rent], method: :delete, data: { confirm: 'Tem certeza?' } %></p>

          	<% end %>
          <% else %>
            
            <p>Nenhum!</p>
            <%= link_to 'Alugar este livro', new_book_rent_path(@book), :class => "btn btn-success" %>

          <% end %>
          
    </div> 	
   </div> 
  </div>  


<% if user_signed_in? %>
  <%= link_to 'Editar', edit_book_path(@book), :class => "btn btn-default" %> 
<% end %> 
<%= link_to 'Voltar', root_path, :class => "btn btn-default" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> <%= @title %> | Biblioteca CITi </title>
		<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>		
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		
		<div class="container-fluid">
			<% if controller_name != ('books')  %>
				<div id="header">
					
					<%= image_tag("logo.png") %>
					<!--h1>Biblioteca CITi</h1-->
					
				</div>
			<% end %>	
				
				<div class="row">	
					
						
				
					<div class="col-md-2"></div>
					<div class="col-md-8" id="main-cont">
						
						<%= render "shared/navbar" %>
						
						<% flash.each do |key, value| %>
    						<div class="alert alert-<%= key %>"><%= value %></div>
  						<% end %>

						<div class="container-fluid">
							<div class="row">
								<%= yield %>
							</div>	
						</div>
					</div>
				</div>
			
		</div>
			
	</body>
</html>

app/views/rents/_form.html.erb
<%= form_for([@book, @rent]) do |f| %>
  <% if @rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% @rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
  </div>
    <%= f.hidden_field :due_date, :value => 10.minutes.from_now %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rents/edit.html.erb
<h1>Editing rent</h1>

<%= render 'form' %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<h1>Listing rents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.name %></td>
        <td><%= rent.email %></td>
        <td><%= rent.due_date %></td>
        <td><%= link_to 'Show', rent %></td>
        <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rent', new_rent_path %>

app/views/rents/new.html.erb
<h1>New rent</h1>

<%= render 'form' %>

<%= link_to 'Back', @book %>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rent.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @rent.email %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @rent.due_date %>
</p>

<%= link_to 'Back', @rent.book %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to "CITi", root_path,:class => "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <%= form_tag books_path, :method => 'get', :class => "navbar-form navbar-left" do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Digite o título do livro" %>
        <%= submit_tag "Pesquisar", :class => "btn btn-default" , name: nil %>
      </div>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><a><b><%= current_user.email %></b></a></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </li>
  </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if !@pesquisa.nil? %>
  
    <table class="table table-striped ">
     
      <tbody>
       <% @pesquisa.each do |book| %> 
        <tr>
          <td><%= link_to book.title, book %></td>
          <td><%= book.author %></td>
          <% if book.taken %>    
            <td class="statusBar"><a class="alert alert-danger status"> Alugado!</a></td>
          <% else %>
              <td class="statusBar"><a class="alert alert-success status"> Disponível! </a></td>
             </div>
          <% end %>     
        
        </tr>
      <% end %>
      </tbody>
    </table>


  



<% end %>